# Generated by Django 2.2.8 on 2019-12-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_create_poll_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterModelOptions(
            name='pollanswer',
            options={'verbose_name': 'PollAnswer', 'verbose_name_plural': 'PollAnswers'},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'verbose_name': 'PollOption', 'verbose_name_plural': 'PollOptions'},
        ),
    ]
