# Generated by Django 2.2.8 on 2019-12-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_creat_vote_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
