# Generated by Django 2.2.8 on 2019-12-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_make_topic_title_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['date_created'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['date_created'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
    ]
